### PR TITLE
added missing toArray trait

### PR DESCRIPTION
**Pull request by mathijsm0**
I was not able to call toArray() on the EboekhoudenRelation Model.
Added the interface and trait.

### CODE REVIEW

**Comment by marnickmenting** [comment]
Yes, came across this issue also, probably related to upgrading to PHP 8.2

**Comment by marnickmenting** [comment]
It doesn't work unfortunately. ProtectedFieldsToArrayTrait expects the values of an array to be arrayable, which the custom_fields variable is not. You could change line 13 to:

```
fn ($item): array => method_exists($item, 'toArray') ? $item->toArray() : $item,
```

**Comment by marnickmenting** [comment]
I have added a new pull request https://github.com/IntVent/eboekhouden-php/pull/16, but it fails because it checks for PHP 7.4. I think that test can be removed. If the maintainer doesn't want to drop support for 7.4, I can remove the typed returns.

**Comment by mathijsm0** [comment]
Made changes as @marnickmenting suggested, while keeping PHP7.4 support.

**Comment by petericebear** [comment]
Sorry for the late response guys. I am looking at the Pull Requests, and yes I will remove the support for it and make a new major version where I will remove the PHP7.4. Thanks for the contributions!

**Pull request merged**
